spring:
  devtools:
    add-properties: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 3000
      idleTimeout: 60000
      maxLifetime: 180000
      maximum-pool-size: 50
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    initialize: false
    properties:
      hibernate:
        generate_statistics: false
    defer-datasource-initialization: false
    show-sql: false
  h2:
    console:
      enabled: false
  data:
    properties:
      hibernate:
        ddl-auto: false
        show-sql: false
        format_sql: false
        globally_quoted_identifiers: false
        globally_quoted_identifiers_skip_column_definitions: false
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: WARN