server:
  servlet:
    contextPath: '/api'
spring:
  profiles:
    active: @activatedProperties@
  main:
    allow-circular-references: true
  application:
    name: '@project.artifactId@-@project.version@'
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: NON_NULL
    locale: pt-BR
    time-zone: America/Sao_Paulo
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: WARN
jwt:
  secret: DF733656293A19C54F69093BA916F0A1A2A3C151FC95C13F3A794C2631EEB3A6