create table usuario (id bigint generated by default as identity, email varchar(255), nome varchar(255), primary key (id));

insert into usuario(id, nome, email) values (1, 'João Silva', 'joao.silva@email.com');
insert into usuario(id, nome, email) values (2, 'Maria Santos', 'maria.santos@email.com');
insert into usuario(id, nome, email) values (3, 'Pedro Almeida', 'pedro.almeida@email.com');
insert into usuario(id, nome, email) values (4, 'Ana Oliveira', 'ana.oliveira@email.com');
insert into usuario(id, nome, email) values (5, 'Carlos Pereira', 'carlos.pereira@email.com');
insert into usuario(id, nome, email) values (6, 'Administrador', 'admin@email.com');