spring:
data:
   rest:
      defaultMediaType: application/json
      basePath: /api
   datasource:
       driverClassName: org.h2.Driver
       url: jdbc:h2:mem:forum
       username: sa
       password:
   jpa:
       database-platform: org.hibernate.dialect.H2Dialect
       initialize: false
       defer-datasource-initialization: false
       show-sql: true
   h2:
     console:
       enabled: true
   properties:
       hibernate:
         ddl-auto: false
         show-sql: true
         format_sql: true
         globally_quoted_identifiers: true
         globally_quoted_identifiers_skip_column_definitions: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#            descriptor:
#                sql:
#                    BasicBinder: INFO
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: INFO
#            StatementCreatorUtils: WARN
